// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: soapbox/notifications/v1/notifications.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category   string                            `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Alert      *Notification_Alert               `protobuf:"bytes,2,opt,name=alert,proto3" json:"alert,omitempty"`
	Arguments  map[string]*Notification_Argument `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CollapseId string                            `protobuf:"bytes,4,opt,name=collapse_id,json=collapseId,proto3" json:"collapse_id,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soapbox_notifications_v1_notifications_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_soapbox_notifications_v1_notifications_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_soapbox_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Notification) GetAlert() *Notification_Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *Notification) GetArguments() map[string]*Notification_Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Notification) GetCollapseId() string {
	if x != nil {
		return x.CollapseId
	}
	return ""
}

type Notification_Argument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Notification_Argument_Int
	//	*Notification_Argument_Str
	Value isNotification_Argument_Value `protobuf_oneof:"value"`
}

func (x *Notification_Argument) Reset() {
	*x = Notification_Argument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soapbox_notifications_v1_notifications_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification_Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification_Argument) ProtoMessage() {}

func (x *Notification_Argument) ProtoReflect() protoreflect.Message {
	mi := &file_soapbox_notifications_v1_notifications_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification_Argument.ProtoReflect.Descriptor instead.
func (*Notification_Argument) Descriptor() ([]byte, []int) {
	return file_soapbox_notifications_v1_notifications_proto_rawDescGZIP(), []int{0, 0}
}

func (m *Notification_Argument) GetValue() isNotification_Argument_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Notification_Argument) GetInt() int64 {
	if x, ok := x.GetValue().(*Notification_Argument_Int); ok {
		return x.Int
	}
	return 0
}

func (x *Notification_Argument) GetStr() string {
	if x, ok := x.GetValue().(*Notification_Argument_Str); ok {
		return x.Str
	}
	return ""
}

type isNotification_Argument_Value interface {
	isNotification_Argument_Value()
}

type Notification_Argument_Int struct {
	Int int64 `protobuf:"varint,1,opt,name=int,proto3,oneof"`
}

type Notification_Argument_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

func (*Notification_Argument_Int) isNotification_Argument_Value() {}

func (*Notification_Argument_Str) isNotification_Argument_Value() {}

type Notification_Alert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body                  string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	LocalizationKey       string   `protobuf:"bytes,2,opt,name=localization_key,json=localizationKey,proto3" json:"localization_key,omitempty"`
	LocalizationArguments []string `protobuf:"bytes,3,rep,name=localization_arguments,json=localizationArguments,proto3" json:"localization_arguments,omitempty"`
}

func (x *Notification_Alert) Reset() {
	*x = Notification_Alert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soapbox_notifications_v1_notifications_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification_Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification_Alert) ProtoMessage() {}

func (x *Notification_Alert) ProtoReflect() protoreflect.Message {
	mi := &file_soapbox_notifications_v1_notifications_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification_Alert.ProtoReflect.Descriptor instead.
func (*Notification_Alert) Descriptor() ([]byte, []int) {
	return file_soapbox_notifications_v1_notifications_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Notification_Alert) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification_Alert) GetLocalizationKey() string {
	if x != nil {
		return x.LocalizationKey
	}
	return ""
}

func (x *Notification_Alert) GetLocalizationArguments() []string {
	if x != nil {
		return x.LocalizationArguments
	}
	return nil
}

var File_soapbox_notifications_v1_notifications_proto protoreflect.FileDescriptor

var file_soapbox_notifications_v1_notifications_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x6f, 0x61, 0x70, 0x62, 0x6f, 0x78, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18,
	0x73, 0x6f, 0x61, 0x70, 0x62, 0x6f, 0x78, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x04, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x42, 0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2c, 0x2e, 0x73, 0x6f, 0x61, 0x70, 0x62, 0x6f, 0x78, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x05, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x12, 0x53, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x73, 0x6f, 0x61, 0x70, 0x62, 0x6f,
	0x78, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c,
	0x6c, 0x61, 0x70, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x49, 0x64, 0x1a, 0x3b, 0x0a, 0x08, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x42, 0x07,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x7d, 0x0a, 0x05, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x35, 0x0a, 0x16, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x15, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x6d, 0x0a, 0x0e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x45, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x6f, 0x61, 0x70,
	0x62, 0x6f, 0x78, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_soapbox_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_soapbox_notifications_v1_notifications_proto_rawDescData = file_soapbox_notifications_v1_notifications_proto_rawDesc
)

func file_soapbox_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_soapbox_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_soapbox_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(file_soapbox_notifications_v1_notifications_proto_rawDescData)
	})
	return file_soapbox_notifications_v1_notifications_proto_rawDescData
}

var file_soapbox_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_soapbox_notifications_v1_notifications_proto_goTypes = []interface{}{
	(*Notification)(nil),          // 0: soapbox.notifications.v1.Notification
	(*Notification_Argument)(nil), // 1: soapbox.notifications.v1.Notification.Argument
	(*Notification_Alert)(nil),    // 2: soapbox.notifications.v1.Notification.Alert
	nil,                           // 3: soapbox.notifications.v1.Notification.ArgumentsEntry
}
var file_soapbox_notifications_v1_notifications_proto_depIdxs = []int32{
	2, // 0: soapbox.notifications.v1.Notification.alert:type_name -> soapbox.notifications.v1.Notification.Alert
	3, // 1: soapbox.notifications.v1.Notification.arguments:type_name -> soapbox.notifications.v1.Notification.ArgumentsEntry
	1, // 2: soapbox.notifications.v1.Notification.ArgumentsEntry.value:type_name -> soapbox.notifications.v1.Notification.Argument
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_soapbox_notifications_v1_notifications_proto_init() }
func file_soapbox_notifications_v1_notifications_proto_init() {
	if File_soapbox_notifications_v1_notifications_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_soapbox_notifications_v1_notifications_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soapbox_notifications_v1_notifications_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification_Argument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soapbox_notifications_v1_notifications_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification_Alert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_soapbox_notifications_v1_notifications_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Notification_Argument_Int)(nil),
		(*Notification_Argument_Str)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_soapbox_notifications_v1_notifications_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_soapbox_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_soapbox_notifications_v1_notifications_proto_depIdxs,
		MessageInfos:      file_soapbox_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_soapbox_notifications_v1_notifications_proto = out.File
	file_soapbox_notifications_v1_notifications_proto_rawDesc = nil
	file_soapbox_notifications_v1_notifications_proto_goTypes = nil
	file_soapbox_notifications_v1_notifications_proto_depIdxs = nil
}
