# -*- mode: ruby -*-
# vi: set ft=ruby :

provisioned = File.exists?(File.join(__dir__, 'provisioned'))

Vagrant.configure(2) do |config|

  config.vm.box = 'bento/centos-7.7'
  config.vm.box_check_update = false
  config.vm.hostname = 'jukebox'
  config.vbguest.auto_update = false

  if provisioned
    config.vm.synced_folder '../', '/var/www', create: true, owner: 'nginx',  group: 'nginx', mount_options: ['dmode=775', 'fmode=775']
  else
    config.vm.synced_folder '../', '/var/www', create: true
  end

  config.vm.network :private_network, ip: '192.168.33.16'
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 50051, host: 50051

  config.vm.provision :shell, path: 'bin/provision.sh', privileged: true
  config.vm.provision :shell, path: 'bin/boot.sh', privileged: true, run: :always

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  end

end
