[redis]
host = "localhost"
port = 6379
database = 0

[db]
host = "127.0.0.1"
port = 5432
user = "voicely"
password = "voicely"
database = "voicely"
ssl = "disable"

[grpc]
host = "127.0.0.1"
port = 50052

[api]
port = 8082

[sfu]
withstats = false

[sfu.webrtc.iceserver]
urls = [
    "stun:stun.l.google.com:19302",
    "stun:stun1.l.google.com:19302",
    "stun:stun2.l.google.com:19302",
    "stun:stun3.l.google.com:19302",
    "stun:stun4.l.google.com:19302",
]

[sfu.router]
withstats = false
audiolevelthreshold = 40
audiolevelinterval=500
audiolevelfilter = 20

#Birds
[[mini]]
key = "03ba569d-1577-43f0-8acb-602f0c2ca720"
id = 12

#Trivia
[[mini]]
key = "198ba444-55b7-47c6-8cb5-5cc912f83ea4"
id = 10

#Draw with Friends
[[mini]]
key = "349c0163-8049-4453-a067-aca72bb51254"
id = 14

