// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: room.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Visibility int32

const (
	Visibility_PUBLIC  Visibility = 0
	Visibility_PRIVATE Visibility = 1
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "PUBLIC",
		1: "PRIVATE",
	}
	Visibility_value = map[string]int32{
		"PUBLIC":  0,
		"PRIVATE": 1,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

type RoomState_RoomMember_Role int32

const (
	RoomState_RoomMember_REGULAR RoomState_RoomMember_Role = 0
	RoomState_RoomMember_ADMIN   RoomState_RoomMember_Role = 1
)

// Enum value maps for RoomState_RoomMember_Role.
var (
	RoomState_RoomMember_Role_name = map[int32]string{
		0: "REGULAR",
		1: "ADMIN",
	}
	RoomState_RoomMember_Role_value = map[string]int32{
		"REGULAR": 0,
		"ADMIN":   1,
	}
)

func (x RoomState_RoomMember_Role) Enum() *RoomState_RoomMember_Role {
	p := new(RoomState_RoomMember_Role)
	*p = x
	return p
}

func (x RoomState_RoomMember_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomState_RoomMember_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[1].Descriptor()
}

func (RoomState_RoomMember_Role) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[1]
}

func (x RoomState_RoomMember_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomState_RoomMember_Role.Descriptor instead.
func (RoomState_RoomMember_Role) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2, 0, 0}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*Command_MuteUpdate_
	//	*Command_Reaction_
	//	*Command_LinkShare_
	//	*Command_InviteAdmin_
	//	*Command_AcceptAdmin_
	//	*Command_RemoveAdmin_
	//	*Command_RenameRoom_
	//	*Command_InviteUser_
	//	*Command_KickUser_
	//	*Command_MuteUser_
	//	*Command_RecordScreen_
	//	*Command_VisibilityUpdate_
	//	*Command_PinLink_
	//	*Command_UnpinLink_
	//	*Command_OpenMini_
	//	*Command_CloseMini_
	Payload isCommand_Payload `protobuf_oneof:"payload"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (m *Command) GetPayload() isCommand_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Command) GetMuteUpdate() *Command_MuteUpdate {
	if x, ok := x.GetPayload().(*Command_MuteUpdate_); ok {
		return x.MuteUpdate
	}
	return nil
}

func (x *Command) GetReaction() *Command_Reaction {
	if x, ok := x.GetPayload().(*Command_Reaction_); ok {
		return x.Reaction
	}
	return nil
}

func (x *Command) GetLinkShare() *Command_LinkShare {
	if x, ok := x.GetPayload().(*Command_LinkShare_); ok {
		return x.LinkShare
	}
	return nil
}

func (x *Command) GetInviteAdmin() *Command_InviteAdmin {
	if x, ok := x.GetPayload().(*Command_InviteAdmin_); ok {
		return x.InviteAdmin
	}
	return nil
}

func (x *Command) GetAcceptAdmin() *Command_AcceptAdmin {
	if x, ok := x.GetPayload().(*Command_AcceptAdmin_); ok {
		return x.AcceptAdmin
	}
	return nil
}

func (x *Command) GetRemoveAdmin() *Command_RemoveAdmin {
	if x, ok := x.GetPayload().(*Command_RemoveAdmin_); ok {
		return x.RemoveAdmin
	}
	return nil
}

func (x *Command) GetRenameRoom() *Command_RenameRoom {
	if x, ok := x.GetPayload().(*Command_RenameRoom_); ok {
		return x.RenameRoom
	}
	return nil
}

func (x *Command) GetInviteUser() *Command_InviteUser {
	if x, ok := x.GetPayload().(*Command_InviteUser_); ok {
		return x.InviteUser
	}
	return nil
}

func (x *Command) GetKickUser() *Command_KickUser {
	if x, ok := x.GetPayload().(*Command_KickUser_); ok {
		return x.KickUser
	}
	return nil
}

func (x *Command) GetMuteUser() *Command_MuteUser {
	if x, ok := x.GetPayload().(*Command_MuteUser_); ok {
		return x.MuteUser
	}
	return nil
}

func (x *Command) GetRecordScreen() *Command_RecordScreen {
	if x, ok := x.GetPayload().(*Command_RecordScreen_); ok {
		return x.RecordScreen
	}
	return nil
}

func (x *Command) GetVisibilityUpdate() *Command_VisibilityUpdate {
	if x, ok := x.GetPayload().(*Command_VisibilityUpdate_); ok {
		return x.VisibilityUpdate
	}
	return nil
}

func (x *Command) GetPinLink() *Command_PinLink {
	if x, ok := x.GetPayload().(*Command_PinLink_); ok {
		return x.PinLink
	}
	return nil
}

func (x *Command) GetUnpinLink() *Command_UnpinLink {
	if x, ok := x.GetPayload().(*Command_UnpinLink_); ok {
		return x.UnpinLink
	}
	return nil
}

func (x *Command) GetOpenMini() *Command_OpenMini {
	if x, ok := x.GetPayload().(*Command_OpenMini_); ok {
		return x.OpenMini
	}
	return nil
}

func (x *Command) GetCloseMini() *Command_CloseMini {
	if x, ok := x.GetPayload().(*Command_CloseMini_); ok {
		return x.CloseMini
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_MuteUpdate_ struct {
	MuteUpdate *Command_MuteUpdate `protobuf:"bytes,1,opt,name=muteUpdate,proto3,oneof"`
}

type Command_Reaction_ struct {
	Reaction *Command_Reaction `protobuf:"bytes,2,opt,name=reaction,proto3,oneof"`
}

type Command_LinkShare_ struct {
	LinkShare *Command_LinkShare `protobuf:"bytes,3,opt,name=linkShare,proto3,oneof"`
}

type Command_InviteAdmin_ struct {
	InviteAdmin *Command_InviteAdmin `protobuf:"bytes,4,opt,name=inviteAdmin,proto3,oneof"`
}

type Command_AcceptAdmin_ struct {
	AcceptAdmin *Command_AcceptAdmin `protobuf:"bytes,5,opt,name=acceptAdmin,proto3,oneof"`
}

type Command_RemoveAdmin_ struct {
	RemoveAdmin *Command_RemoveAdmin `protobuf:"bytes,6,opt,name=removeAdmin,proto3,oneof"`
}

type Command_RenameRoom_ struct {
	RenameRoom *Command_RenameRoom `protobuf:"bytes,7,opt,name=renameRoom,proto3,oneof"`
}

type Command_InviteUser_ struct {
	InviteUser *Command_InviteUser `protobuf:"bytes,8,opt,name=inviteUser,proto3,oneof"`
}

type Command_KickUser_ struct {
	KickUser *Command_KickUser `protobuf:"bytes,9,opt,name=kickUser,proto3,oneof"`
}

type Command_MuteUser_ struct {
	MuteUser *Command_MuteUser `protobuf:"bytes,10,opt,name=muteUser,proto3,oneof"`
}

type Command_RecordScreen_ struct {
	RecordScreen *Command_RecordScreen `protobuf:"bytes,11,opt,name=recordScreen,proto3,oneof"`
}

type Command_VisibilityUpdate_ struct {
	VisibilityUpdate *Command_VisibilityUpdate `protobuf:"bytes,12,opt,name=visibilityUpdate,proto3,oneof"`
}

type Command_PinLink_ struct {
	PinLink *Command_PinLink `protobuf:"bytes,13,opt,name=pinLink,proto3,oneof"`
}

type Command_UnpinLink_ struct {
	UnpinLink *Command_UnpinLink `protobuf:"bytes,14,opt,name=unpinLink,proto3,oneof"`
}

type Command_OpenMini_ struct {
	OpenMini *Command_OpenMini `protobuf:"bytes,15,opt,name=openMini,proto3,oneof"`
}

type Command_CloseMini_ struct {
	CloseMini *Command_CloseMini `protobuf:"bytes,16,opt,name=closeMini,proto3,oneof"`
}

func (*Command_MuteUpdate_) isCommand_Payload() {}

func (*Command_Reaction_) isCommand_Payload() {}

func (*Command_LinkShare_) isCommand_Payload() {}

func (*Command_InviteAdmin_) isCommand_Payload() {}

func (*Command_AcceptAdmin_) isCommand_Payload() {}

func (*Command_RemoveAdmin_) isCommand_Payload() {}

func (*Command_RenameRoom_) isCommand_Payload() {}

func (*Command_InviteUser_) isCommand_Payload() {}

func (*Command_KickUser_) isCommand_Payload() {}

func (*Command_MuteUser_) isCommand_Payload() {}

func (*Command_RecordScreen_) isCommand_Payload() {}

func (*Command_VisibilityUpdate_) isCommand_Payload() {}

func (*Command_PinLink_) isCommand_Payload() {}

func (*Command_UnpinLink_) isCommand_Payload() {}

func (*Command_OpenMini_) isCommand_Payload() {}

func (*Command_CloseMini_) isCommand_Payload() {}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// Types that are assignable to Payload:
	//	*Event_Joined_
	//	*Event_Left_
	//	*Event_MuteUpdated_
	//	*Event_Reacted_
	//	*Event_LinkShared_
	//	*Event_InvitedAdmin_
	//	*Event_AddedAdmin_
	//	*Event_RemovedAdmin_
	//	*Event_RenamedRoom_
	//	*Event_RecordedScreen_
	//	*Event_MutedByAdmin_
	//	*Event_VisibilityUpdated_
	//	*Event_PinnedLink_
	//	*Event_UnpinnedLink_
	//	*Event_OpenedMini_
	//	*Event_ClosedMini_
	Payload isEvent_Payload `protobuf_oneof:"payload"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (m *Event) GetPayload() isEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Event) GetJoined() *Event_Joined {
	if x, ok := x.GetPayload().(*Event_Joined_); ok {
		return x.Joined
	}
	return nil
}

func (x *Event) GetLeft() *Event_Left {
	if x, ok := x.GetPayload().(*Event_Left_); ok {
		return x.Left
	}
	return nil
}

func (x *Event) GetMuteUpdated() *Event_MuteUpdated {
	if x, ok := x.GetPayload().(*Event_MuteUpdated_); ok {
		return x.MuteUpdated
	}
	return nil
}

func (x *Event) GetReacted() *Event_Reacted {
	if x, ok := x.GetPayload().(*Event_Reacted_); ok {
		return x.Reacted
	}
	return nil
}

func (x *Event) GetLinkShared() *Event_LinkShared {
	if x, ok := x.GetPayload().(*Event_LinkShared_); ok {
		return x.LinkShared
	}
	return nil
}

func (x *Event) GetInvitedAdmin() *Event_InvitedAdmin {
	if x, ok := x.GetPayload().(*Event_InvitedAdmin_); ok {
		return x.InvitedAdmin
	}
	return nil
}

func (x *Event) GetAddedAdmin() *Event_AddedAdmin {
	if x, ok := x.GetPayload().(*Event_AddedAdmin_); ok {
		return x.AddedAdmin
	}
	return nil
}

func (x *Event) GetRemovedAdmin() *Event_RemovedAdmin {
	if x, ok := x.GetPayload().(*Event_RemovedAdmin_); ok {
		return x.RemovedAdmin
	}
	return nil
}

func (x *Event) GetRenamedRoom() *Event_RenamedRoom {
	if x, ok := x.GetPayload().(*Event_RenamedRoom_); ok {
		return x.RenamedRoom
	}
	return nil
}

func (x *Event) GetRecordedScreen() *Event_RecordedScreen {
	if x, ok := x.GetPayload().(*Event_RecordedScreen_); ok {
		return x.RecordedScreen
	}
	return nil
}

func (x *Event) GetMutedByAdmin() *Event_MutedByAdmin {
	if x, ok := x.GetPayload().(*Event_MutedByAdmin_); ok {
		return x.MutedByAdmin
	}
	return nil
}

func (x *Event) GetVisibilityUpdated() *Event_VisibilityUpdated {
	if x, ok := x.GetPayload().(*Event_VisibilityUpdated_); ok {
		return x.VisibilityUpdated
	}
	return nil
}

func (x *Event) GetPinnedLink() *Event_PinnedLink {
	if x, ok := x.GetPayload().(*Event_PinnedLink_); ok {
		return x.PinnedLink
	}
	return nil
}

func (x *Event) GetUnpinnedLink() *Event_UnpinnedLink {
	if x, ok := x.GetPayload().(*Event_UnpinnedLink_); ok {
		return x.UnpinnedLink
	}
	return nil
}

func (x *Event) GetOpenedMini() *Event_OpenedMini {
	if x, ok := x.GetPayload().(*Event_OpenedMini_); ok {
		return x.OpenedMini
	}
	return nil
}

func (x *Event) GetClosedMini() *Event_ClosedMini {
	if x, ok := x.GetPayload().(*Event_ClosedMini_); ok {
		return x.ClosedMini
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Joined_ struct {
	Joined *Event_Joined `protobuf:"bytes,2,opt,name=joined,proto3,oneof"`
}

type Event_Left_ struct {
	Left *Event_Left `protobuf:"bytes,3,opt,name=left,proto3,oneof"`
}

type Event_MuteUpdated_ struct {
	MuteUpdated *Event_MuteUpdated `protobuf:"bytes,4,opt,name=muteUpdated,proto3,oneof"`
}

type Event_Reacted_ struct {
	Reacted *Event_Reacted `protobuf:"bytes,5,opt,name=reacted,proto3,oneof"`
}

type Event_LinkShared_ struct {
	LinkShared *Event_LinkShared `protobuf:"bytes,6,opt,name=linkShared,proto3,oneof"`
}

type Event_InvitedAdmin_ struct {
	InvitedAdmin *Event_InvitedAdmin `protobuf:"bytes,7,opt,name=invitedAdmin,proto3,oneof"`
}

type Event_AddedAdmin_ struct {
	AddedAdmin *Event_AddedAdmin `protobuf:"bytes,8,opt,name=addedAdmin,proto3,oneof"`
}

type Event_RemovedAdmin_ struct {
	RemovedAdmin *Event_RemovedAdmin `protobuf:"bytes,9,opt,name=removedAdmin,proto3,oneof"`
}

type Event_RenamedRoom_ struct {
	RenamedRoom *Event_RenamedRoom `protobuf:"bytes,10,opt,name=renamedRoom,proto3,oneof"`
}

type Event_RecordedScreen_ struct {
	RecordedScreen *Event_RecordedScreen `protobuf:"bytes,11,opt,name=recordedScreen,proto3,oneof"`
}

type Event_MutedByAdmin_ struct {
	MutedByAdmin *Event_MutedByAdmin `protobuf:"bytes,12,opt,name=mutedByAdmin,proto3,oneof"`
}

type Event_VisibilityUpdated_ struct {
	VisibilityUpdated *Event_VisibilityUpdated `protobuf:"bytes,13,opt,name=visibilityUpdated,proto3,oneof"`
}

type Event_PinnedLink_ struct {
	PinnedLink *Event_PinnedLink `protobuf:"bytes,14,opt,name=pinnedLink,proto3,oneof"`
}

type Event_UnpinnedLink_ struct {
	UnpinnedLink *Event_UnpinnedLink `protobuf:"bytes,15,opt,name=unpinnedLink,proto3,oneof"`
}

type Event_OpenedMini_ struct {
	OpenedMini *Event_OpenedMini `protobuf:"bytes,16,opt,name=openedMini,proto3,oneof"`
}

type Event_ClosedMini_ struct {
	ClosedMini *Event_ClosedMini `protobuf:"bytes,17,opt,name=closedMini,proto3,oneof"`
}

func (*Event_Joined_) isEvent_Payload() {}

func (*Event_Left_) isEvent_Payload() {}

func (*Event_MuteUpdated_) isEvent_Payload() {}

func (*Event_Reacted_) isEvent_Payload() {}

func (*Event_LinkShared_) isEvent_Payload() {}

func (*Event_InvitedAdmin_) isEvent_Payload() {}

func (*Event_AddedAdmin_) isEvent_Payload() {}

func (*Event_RemovedAdmin_) isEvent_Payload() {}

func (*Event_RenamedRoom_) isEvent_Payload() {}

func (*Event_RecordedScreen_) isEvent_Payload() {}

func (*Event_MutedByAdmin_) isEvent_Payload() {}

func (*Event_VisibilityUpdated_) isEvent_Payload() {}

func (*Event_PinnedLink_) isEvent_Payload() {}

func (*Event_UnpinnedLink_) isEvent_Payload() {}

func (*Event_OpenedMini_) isEvent_Payload() {}

func (*Event_ClosedMini_) isEvent_Payload() {}

type RoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members    []*RoomState_RoomMember `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Role       string                  `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // @TODO THINK ABOUT ENUM
	Visibility Visibility              `protobuf:"varint,5,opt,name=visibility,proto3,enum=Visibility" json:"visibility,omitempty"`
	Group      *RoomState_Group        `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Link       string                  `protobuf:"bytes,7,opt,name=link,proto3" json:"link,omitempty"`
	Mini       string                  `protobuf:"bytes,8,opt,name=mini,proto3" json:"mini,omitempty"`
}

func (x *RoomState) Reset() {
	*x = RoomState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState) ProtoMessage() {}

func (x *RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState.ProtoReflect.Descriptor instead.
func (*RoomState) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomState) GetMembers() []*RoomState_RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomState) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RoomState) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_PUBLIC
}

func (x *RoomState) GetGroup() *RoomState_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *RoomState) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RoomState) GetMini() string {
	if x != nil {
		return x.Mini
	}
	return ""
}

type Command_MuteUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Muted bool `protobuf:"varint,1,opt,name=muted,proto3" json:"muted,omitempty"`
}

func (x *Command_MuteUpdate) Reset() {
	*x = Command_MuteUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_MuteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_MuteUpdate) ProtoMessage() {}

func (x *Command_MuteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_MuteUpdate.ProtoReflect.Descriptor instead.
func (*Command_MuteUpdate) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Command_MuteUpdate) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type Command_Reaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emoji []byte `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
}

func (x *Command_Reaction) Reset() {
	*x = Command_Reaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Reaction) ProtoMessage() {}

func (x *Command_Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Reaction.ProtoReflect.Descriptor instead.
func (*Command_Reaction) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Command_Reaction) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type Command_LinkShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Command_LinkShare) Reset() {
	*x = Command_LinkShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_LinkShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_LinkShare) ProtoMessage() {}

func (x *Command_LinkShare) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_LinkShare.ProtoReflect.Descriptor instead.
func (*Command_LinkShare) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Command_LinkShare) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Command_InviteAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_InviteAdmin) Reset() {
	*x = Command_InviteAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_InviteAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_InviteAdmin) ProtoMessage() {}

func (x *Command_InviteAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_InviteAdmin.ProtoReflect.Descriptor instead.
func (*Command_InviteAdmin) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Command_InviteAdmin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Command_AcceptAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Command_AcceptAdmin) Reset() {
	*x = Command_AcceptAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_AcceptAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_AcceptAdmin) ProtoMessage() {}

func (x *Command_AcceptAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_AcceptAdmin.ProtoReflect.Descriptor instead.
func (*Command_AcceptAdmin) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 4}
}

type Command_RemoveAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_RemoveAdmin) Reset() {
	*x = Command_RemoveAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_RemoveAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_RemoveAdmin) ProtoMessage() {}

func (x *Command_RemoveAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_RemoveAdmin.ProtoReflect.Descriptor instead.
func (*Command_RemoveAdmin) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Command_RemoveAdmin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Command_RenameRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Command_RenameRoom) Reset() {
	*x = Command_RenameRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_RenameRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_RenameRoom) ProtoMessage() {}

func (x *Command_RenameRoom) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_RenameRoom.ProtoReflect.Descriptor instead.
func (*Command_RenameRoom) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Command_RenameRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Command_InviteUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_InviteUser) Reset() {
	*x = Command_InviteUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_InviteUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_InviteUser) ProtoMessage() {}

func (x *Command_InviteUser) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_InviteUser.ProtoReflect.Descriptor instead.
func (*Command_InviteUser) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Command_InviteUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Command_KickUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_KickUser) Reset() {
	*x = Command_KickUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_KickUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_KickUser) ProtoMessage() {}

func (x *Command_KickUser) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_KickUser.ProtoReflect.Descriptor instead.
func (*Command_KickUser) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Command_KickUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Command_MuteUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_MuteUser) Reset() {
	*x = Command_MuteUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_MuteUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_MuteUser) ProtoMessage() {}

func (x *Command_MuteUser) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_MuteUser.ProtoReflect.Descriptor instead.
func (*Command_MuteUser) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Command_MuteUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Command_RecordScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Command_RecordScreen) Reset() {
	*x = Command_RecordScreen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_RecordScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_RecordScreen) ProtoMessage() {}

func (x *Command_RecordScreen) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_RecordScreen.ProtoReflect.Descriptor instead.
func (*Command_RecordScreen) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 10}
}

type Command_VisibilityUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visibility Visibility `protobuf:"varint,1,opt,name=visibility,proto3,enum=Visibility" json:"visibility,omitempty"`
}

func (x *Command_VisibilityUpdate) Reset() {
	*x = Command_VisibilityUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_VisibilityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_VisibilityUpdate) ProtoMessage() {}

func (x *Command_VisibilityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_VisibilityUpdate.ProtoReflect.Descriptor instead.
func (*Command_VisibilityUpdate) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Command_VisibilityUpdate) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_PUBLIC
}

type Command_PinLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Command_PinLink) Reset() {
	*x = Command_PinLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_PinLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_PinLink) ProtoMessage() {}

func (x *Command_PinLink) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_PinLink.ProtoReflect.Descriptor instead.
func (*Command_PinLink) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Command_PinLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Command_UnpinLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Command_UnpinLink) Reset() {
	*x = Command_UnpinLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_UnpinLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_UnpinLink) ProtoMessage() {}

func (x *Command_UnpinLink) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_UnpinLink.ProtoReflect.Descriptor instead.
func (*Command_UnpinLink) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 13}
}

type Command_OpenMini struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mini string `protobuf:"bytes,1,opt,name=mini,proto3" json:"mini,omitempty"`
}

func (x *Command_OpenMini) Reset() {
	*x = Command_OpenMini{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_OpenMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_OpenMini) ProtoMessage() {}

func (x *Command_OpenMini) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_OpenMini.ProtoReflect.Descriptor instead.
func (*Command_OpenMini) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 14}
}

func (x *Command_OpenMini) GetMini() string {
	if x != nil {
		return x.Mini
	}
	return ""
}

type Command_CloseMini struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Command_CloseMini) Reset() {
	*x = Command_CloseMini{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_CloseMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_CloseMini) ProtoMessage() {}

func (x *Command_CloseMini) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_CloseMini.ProtoReflect.Descriptor instead.
func (*Command_CloseMini) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0, 15}
}

type Event_Joined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *RoomState_RoomMember `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Event_Joined) Reset() {
	*x = Event_Joined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_Joined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Joined) ProtoMessage() {}

func (x *Event_Joined) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Joined.ProtoReflect.Descriptor instead.
func (*Event_Joined) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Event_Joined) GetUser() *RoomState_RoomMember {
	if x != nil {
		return x.User
	}
	return nil
}

type Event_Left struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Event_Left) Reset() {
	*x = Event_Left{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_Left) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Left) ProtoMessage() {}

func (x *Event_Left) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Left.ProtoReflect.Descriptor instead.
func (*Event_Left) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Event_Left) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event_MuteUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMuted bool `protobuf:"varint,1,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
}

func (x *Event_MuteUpdated) Reset() {
	*x = Event_MuteUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_MuteUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_MuteUpdated) ProtoMessage() {}

func (x *Event_MuteUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_MuteUpdated.ProtoReflect.Descriptor instead.
func (*Event_MuteUpdated) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Event_MuteUpdated) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

type Event_Reacted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emoji []byte `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
}

func (x *Event_Reacted) Reset() {
	*x = Event_Reacted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_Reacted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Reacted) ProtoMessage() {}

func (x *Event_Reacted) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Reacted.ProtoReflect.Descriptor instead.
func (*Event_Reacted) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Event_Reacted) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type Event_LinkShared struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Event_LinkShared) Reset() {
	*x = Event_LinkShared{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_LinkShared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_LinkShared) ProtoMessage() {}

func (x *Event_LinkShared) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_LinkShared.ProtoReflect.Descriptor instead.
func (*Event_LinkShared) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 4}
}

func (x *Event_LinkShared) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Event_InvitedAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Event_InvitedAdmin) Reset() {
	*x = Event_InvitedAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_InvitedAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_InvitedAdmin) ProtoMessage() {}

func (x *Event_InvitedAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_InvitedAdmin.ProtoReflect.Descriptor instead.
func (*Event_InvitedAdmin) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 5}
}

func (x *Event_InvitedAdmin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event_AddedAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Event_AddedAdmin) Reset() {
	*x = Event_AddedAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_AddedAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_AddedAdmin) ProtoMessage() {}

func (x *Event_AddedAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_AddedAdmin.ProtoReflect.Descriptor instead.
func (*Event_AddedAdmin) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 6}
}

func (x *Event_AddedAdmin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event_RemovedAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Event_RemovedAdmin) Reset() {
	*x = Event_RemovedAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_RemovedAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_RemovedAdmin) ProtoMessage() {}

func (x *Event_RemovedAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_RemovedAdmin.ProtoReflect.Descriptor instead.
func (*Event_RemovedAdmin) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 7}
}

func (x *Event_RemovedAdmin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event_RenamedRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Event_RenamedRoom) Reset() {
	*x = Event_RenamedRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_RenamedRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_RenamedRoom) ProtoMessage() {}

func (x *Event_RenamedRoom) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_RenamedRoom.ProtoReflect.Descriptor instead.
func (*Event_RenamedRoom) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 8}
}

func (x *Event_RenamedRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Event_RecordedScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Event_RecordedScreen) Reset() {
	*x = Event_RecordedScreen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_RecordedScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_RecordedScreen) ProtoMessage() {}

func (x *Event_RecordedScreen) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_RecordedScreen.ProtoReflect.Descriptor instead.
func (*Event_RecordedScreen) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 9}
}

func (x *Event_RecordedScreen) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event_MutedByAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Event_MutedByAdmin) Reset() {
	*x = Event_MutedByAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_MutedByAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_MutedByAdmin) ProtoMessage() {}

func (x *Event_MutedByAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_MutedByAdmin.ProtoReflect.Descriptor instead.
func (*Event_MutedByAdmin) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 10}
}

func (x *Event_MutedByAdmin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event_VisibilityUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visibility Visibility `protobuf:"varint,1,opt,name=visibility,proto3,enum=Visibility" json:"visibility,omitempty"`
}

func (x *Event_VisibilityUpdated) Reset() {
	*x = Event_VisibilityUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_VisibilityUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VisibilityUpdated) ProtoMessage() {}

func (x *Event_VisibilityUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VisibilityUpdated.ProtoReflect.Descriptor instead.
func (*Event_VisibilityUpdated) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 11}
}

func (x *Event_VisibilityUpdated) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_PUBLIC
}

type Event_PinnedLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Event_PinnedLink) Reset() {
	*x = Event_PinnedLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_PinnedLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_PinnedLink) ProtoMessage() {}

func (x *Event_PinnedLink) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_PinnedLink.ProtoReflect.Descriptor instead.
func (*Event_PinnedLink) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 12}
}

func (x *Event_PinnedLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Event_UnpinnedLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Event_UnpinnedLink) Reset() {
	*x = Event_UnpinnedLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_UnpinnedLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_UnpinnedLink) ProtoMessage() {}

func (x *Event_UnpinnedLink) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_UnpinnedLink.ProtoReflect.Descriptor instead.
func (*Event_UnpinnedLink) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 13}
}

type Event_OpenedMini struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mini string `protobuf:"bytes,1,opt,name=mini,proto3" json:"mini,omitempty"`
}

func (x *Event_OpenedMini) Reset() {
	*x = Event_OpenedMini{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_OpenedMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_OpenedMini) ProtoMessage() {}

func (x *Event_OpenedMini) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_OpenedMini.ProtoReflect.Descriptor instead.
func (*Event_OpenedMini) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 14}
}

func (x *Event_OpenedMini) GetMini() string {
	if x != nil {
		return x.Mini
	}
	return ""
}

type Event_ClosedMini struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Event_ClosedMini) Reset() {
	*x = Event_ClosedMini{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event_ClosedMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_ClosedMini) ProtoMessage() {}

func (x *Event_ClosedMini) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_ClosedMini.ProtoReflect.Descriptor instead.
func (*Event_ClosedMini) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1, 15}
}

type RoomState_RoomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName string                    `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Image       string                    `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Role        RoomState_RoomMember_Role `protobuf:"varint,4,opt,name=role,proto3,enum=RoomState_RoomMember_Role" json:"role,omitempty"`
	Muted       bool                      `protobuf:"varint,5,opt,name=muted,proto3" json:"muted,omitempty"`
	Ssrc        uint32                    `protobuf:"varint,6,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
}

func (x *RoomState_RoomMember) Reset() {
	*x = RoomState_RoomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomState_RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState_RoomMember) ProtoMessage() {}

func (x *RoomState_RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState_RoomMember.ProtoReflect.Descriptor instead.
func (*RoomState_RoomMember) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RoomState_RoomMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomState_RoomMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RoomState_RoomMember) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RoomState_RoomMember) GetRole() RoomState_RoomMember_Role {
	if x != nil {
		return x.Role
	}
	return RoomState_RoomMember_REGULAR
}

func (x *RoomState_RoomMember) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *RoomState_RoomMember) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

type RoomState_Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *RoomState_Group) Reset() {
	*x = RoomState_Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomState_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState_Group) ProtoMessage() {}

func (x *RoomState_Group) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState_Group.ProtoReflect.Descriptor instead.
func (*RoomState_Group) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RoomState_Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomState_Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomState_Group) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_room_proto protoreflect.FileDescriptor

var file_room_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x0a, 0x0a,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x35, 0x0a, 0x0a, 0x6d, 0x75, 0x74, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4d, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x2f, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x32, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48,
	0x00, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x38,
	0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x35, 0x0a, 0x0a, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x00, 0x52, 0x0a, 0x72,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x35, 0x0a, 0x0a, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x2f, 0x0a, 0x08, 0x6b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4b, 0x69, 0x63,
	0x6b, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x6b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x75, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4d, 0x75,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x75, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x48,
	0x00, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12,
	0x47, 0x0a, 0x10, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x10, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x69, 0x6e, 0x4c,
	0x69, 0x6e, 0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x50, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x70,
	0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x32, 0x0a, 0x09, 0x75, 0x6e, 0x70, 0x69, 0x6e, 0x4c,
	0x69, 0x6e, 0x6b, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x55, 0x6e, 0x70, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52,
	0x09, 0x75, 0x6e, 0x70, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x2f, 0x0a, 0x08, 0x6f, 0x70,
	0x65, 0x6e, 0x4d, 0x69, 0x6e, 0x69, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4d, 0x69, 0x6e, 0x69, 0x48,
	0x00, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x4d, 0x69, 0x6e, 0x69, 0x12, 0x32, 0x0a, 0x09, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x69,
	0x6e, 0x69, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x1a,
	0x22, 0x0a, 0x0a, 0x4d, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75,
	0x74, 0x65, 0x64, 0x1a, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x1a, 0x1f, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x1a, 0x1d, 0x0a, 0x0b, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x0d, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x1d, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x1a, 0x20, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x1c, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x1a, 0x1a, 0x0a, 0x08, 0x4b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x1a,
	0x1a, 0x0a, 0x08, 0x4d, 0x75, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x0e, 0x0a, 0x0c, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x1a, 0x3f, 0x0a, 0x10, 0x56,
	0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x2b, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x1a, 0x1d, 0x0a, 0x07,
	0x50, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x1a, 0x0b, 0x0a, 0x09, 0x55,
	0x6e, 0x70, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x1e, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e,
	0x4d, 0x69, 0x6e, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x69, 0x1a, 0x0b, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x4d, 0x69, 0x6e, 0x69, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0xaf, 0x0b, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x27,
	0x0a, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x65,
	0x66, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x36, 0x0a, 0x0b, 0x6d, 0x75,
	0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x6d, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12, 0x33,
	0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x00,
	0x52, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x33,
	0x0a, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x00,
	0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x36,
	0x0a, 0x0b, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x3f, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x65, 0x64, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x64, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65,
	0x64, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x39, 0x0a, 0x0c, 0x6d, 0x75, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x75, 0x74, 0x65, 0x64, 0x42, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x42, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x48, 0x0a, 0x11, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x11, 0x76, 0x69, 0x73, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x0a,
	0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4c,
	0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4c, 0x69, 0x6e,
	0x6b, 0x12, 0x39, 0x0a, 0x0c, 0x75, 0x6e, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4c, 0x69, 0x6e,
	0x6b, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x55, 0x6e, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x0c,
	0x75, 0x6e, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x33, 0x0a, 0x0a,
	0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x4d,
	0x69, 0x6e, 0x69, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x4d, 0x69, 0x6e,
	0x69, 0x12, 0x33, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x1a, 0x33, 0x0a, 0x06, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64,
	0x12, 0x29, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x16, 0x0a, 0x04, 0x4c,
	0x65, 0x66, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x1a, 0x28, 0x0a, 0x0b, 0x4d, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4d, 0x75, 0x74, 0x65, 0x64, 0x1a, 0x1f, 0x0a,
	0x07, 0x52, 0x65, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x6f, 0x6a,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x1a, 0x20,
	0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x1a, 0x1e, 0x0a, 0x0c, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x1a, 0x1c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x1e,
	0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x21,
	0x0a, 0x0b, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x1a, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x64, 0x53, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x1a, 0x1e, 0x0a, 0x0c, 0x4d, 0x75, 0x74, 0x65, 0x64, 0x42, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x1a, 0x40, 0x0a, 0x11, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x56,
	0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x1a, 0x20, 0x0a, 0x0a, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4c,
	0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x1a, 0x0e, 0x0a, 0x0c, 0x55, 0x6e, 0x70, 0x69, 0x6e,
	0x6e, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x20, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x65,
	0x64, 0x4d, 0x69, 0x6e, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x69, 0x1a, 0x0c, 0x0a, 0x0a, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x85, 0x04, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x76, 0x69, 0x73,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x69, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x69, 0x6e, 0x69, 0x1a, 0xce, 0x01, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75,
	0x74, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x73, 0x72, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x73, 0x72, 0x63, 0x22, 0x1e, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x52, 0x45, 0x47, 0x55, 0x4c, 0x41, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x1a, 0x41, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2a, 0x25, 0x0a, 0x0a, 0x56, 0x69,
	0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x55, 0x42, 0x4c,
	0x49, 0x43, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10,
	0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData = file_room_proto_rawDesc
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_proto_rawDescData)
	})
	return file_room_proto_rawDescData
}

var file_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_room_proto_goTypes = []interface{}{
	(Visibility)(0),                  // 0: Visibility
	(RoomState_RoomMember_Role)(0),   // 1: RoomState.RoomMember.Role
	(*Command)(nil),                  // 2: Command
	(*Event)(nil),                    // 3: Event
	(*RoomState)(nil),                // 4: RoomState
	(*Command_MuteUpdate)(nil),       // 5: Command.MuteUpdate
	(*Command_Reaction)(nil),         // 6: Command.Reaction
	(*Command_LinkShare)(nil),        // 7: Command.LinkShare
	(*Command_InviteAdmin)(nil),      // 8: Command.InviteAdmin
	(*Command_AcceptAdmin)(nil),      // 9: Command.AcceptAdmin
	(*Command_RemoveAdmin)(nil),      // 10: Command.RemoveAdmin
	(*Command_RenameRoom)(nil),       // 11: Command.RenameRoom
	(*Command_InviteUser)(nil),       // 12: Command.InviteUser
	(*Command_KickUser)(nil),         // 13: Command.KickUser
	(*Command_MuteUser)(nil),         // 14: Command.MuteUser
	(*Command_RecordScreen)(nil),     // 15: Command.RecordScreen
	(*Command_VisibilityUpdate)(nil), // 16: Command.VisibilityUpdate
	(*Command_PinLink)(nil),          // 17: Command.PinLink
	(*Command_UnpinLink)(nil),        // 18: Command.UnpinLink
	(*Command_OpenMini)(nil),         // 19: Command.OpenMini
	(*Command_CloseMini)(nil),        // 20: Command.CloseMini
	(*Event_Joined)(nil),             // 21: Event.Joined
	(*Event_Left)(nil),               // 22: Event.Left
	(*Event_MuteUpdated)(nil),        // 23: Event.MuteUpdated
	(*Event_Reacted)(nil),            // 24: Event.Reacted
	(*Event_LinkShared)(nil),         // 25: Event.LinkShared
	(*Event_InvitedAdmin)(nil),       // 26: Event.InvitedAdmin
	(*Event_AddedAdmin)(nil),         // 27: Event.AddedAdmin
	(*Event_RemovedAdmin)(nil),       // 28: Event.RemovedAdmin
	(*Event_RenamedRoom)(nil),        // 29: Event.RenamedRoom
	(*Event_RecordedScreen)(nil),     // 30: Event.RecordedScreen
	(*Event_MutedByAdmin)(nil),       // 31: Event.MutedByAdmin
	(*Event_VisibilityUpdated)(nil),  // 32: Event.VisibilityUpdated
	(*Event_PinnedLink)(nil),         // 33: Event.PinnedLink
	(*Event_UnpinnedLink)(nil),       // 34: Event.UnpinnedLink
	(*Event_OpenedMini)(nil),         // 35: Event.OpenedMini
	(*Event_ClosedMini)(nil),         // 36: Event.ClosedMini
	(*RoomState_RoomMember)(nil),     // 37: RoomState.RoomMember
	(*RoomState_Group)(nil),          // 38: RoomState.Group
}
var file_room_proto_depIdxs = []int32{
	5,  // 0: Command.muteUpdate:type_name -> Command.MuteUpdate
	6,  // 1: Command.reaction:type_name -> Command.Reaction
	7,  // 2: Command.linkShare:type_name -> Command.LinkShare
	8,  // 3: Command.inviteAdmin:type_name -> Command.InviteAdmin
	9,  // 4: Command.acceptAdmin:type_name -> Command.AcceptAdmin
	10, // 5: Command.removeAdmin:type_name -> Command.RemoveAdmin
	11, // 6: Command.renameRoom:type_name -> Command.RenameRoom
	12, // 7: Command.inviteUser:type_name -> Command.InviteUser
	13, // 8: Command.kickUser:type_name -> Command.KickUser
	14, // 9: Command.muteUser:type_name -> Command.MuteUser
	15, // 10: Command.recordScreen:type_name -> Command.RecordScreen
	16, // 11: Command.visibilityUpdate:type_name -> Command.VisibilityUpdate
	17, // 12: Command.pinLink:type_name -> Command.PinLink
	18, // 13: Command.unpinLink:type_name -> Command.UnpinLink
	19, // 14: Command.openMini:type_name -> Command.OpenMini
	20, // 15: Command.closeMini:type_name -> Command.CloseMini
	21, // 16: Event.joined:type_name -> Event.Joined
	22, // 17: Event.left:type_name -> Event.Left
	23, // 18: Event.muteUpdated:type_name -> Event.MuteUpdated
	24, // 19: Event.reacted:type_name -> Event.Reacted
	25, // 20: Event.linkShared:type_name -> Event.LinkShared
	26, // 21: Event.invitedAdmin:type_name -> Event.InvitedAdmin
	27, // 22: Event.addedAdmin:type_name -> Event.AddedAdmin
	28, // 23: Event.removedAdmin:type_name -> Event.RemovedAdmin
	29, // 24: Event.renamedRoom:type_name -> Event.RenamedRoom
	30, // 25: Event.recordedScreen:type_name -> Event.RecordedScreen
	31, // 26: Event.mutedByAdmin:type_name -> Event.MutedByAdmin
	32, // 27: Event.visibilityUpdated:type_name -> Event.VisibilityUpdated
	33, // 28: Event.pinnedLink:type_name -> Event.PinnedLink
	34, // 29: Event.unpinnedLink:type_name -> Event.UnpinnedLink
	35, // 30: Event.openedMini:type_name -> Event.OpenedMini
	36, // 31: Event.closedMini:type_name -> Event.ClosedMini
	37, // 32: RoomState.members:type_name -> RoomState.RoomMember
	0,  // 33: RoomState.visibility:type_name -> Visibility
	38, // 34: RoomState.group:type_name -> RoomState.Group
	0,  // 35: Command.VisibilityUpdate.visibility:type_name -> Visibility
	37, // 36: Event.Joined.user:type_name -> RoomState.RoomMember
	0,  // 37: Event.VisibilityUpdated.visibility:type_name -> Visibility
	1,  // 38: RoomState.RoomMember.role:type_name -> RoomState.RoomMember.Role
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_MuteUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_Reaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_LinkShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_InviteAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_AcceptAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_RemoveAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_RenameRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_InviteUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_KickUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_MuteUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_RecordScreen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_VisibilityUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_PinLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_UnpinLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_OpenMini); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_CloseMini); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_Joined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_Left); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_MuteUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_Reacted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_LinkShared); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_InvitedAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_AddedAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_RemovedAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_RenamedRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_RecordedScreen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_MutedByAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_VisibilityUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_PinnedLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_UnpinnedLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_OpenedMini); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event_ClosedMini); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomState_RoomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomState_Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_room_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Command_MuteUpdate_)(nil),
		(*Command_Reaction_)(nil),
		(*Command_LinkShare_)(nil),
		(*Command_InviteAdmin_)(nil),
		(*Command_AcceptAdmin_)(nil),
		(*Command_RemoveAdmin_)(nil),
		(*Command_RenameRoom_)(nil),
		(*Command_InviteUser_)(nil),
		(*Command_KickUser_)(nil),
		(*Command_MuteUser_)(nil),
		(*Command_RecordScreen_)(nil),
		(*Command_VisibilityUpdate_)(nil),
		(*Command_PinLink_)(nil),
		(*Command_UnpinLink_)(nil),
		(*Command_OpenMini_)(nil),
		(*Command_CloseMini_)(nil),
	}
	file_room_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Event_Joined_)(nil),
		(*Event_Left_)(nil),
		(*Event_MuteUpdated_)(nil),
		(*Event_Reacted_)(nil),
		(*Event_LinkShared_)(nil),
		(*Event_InvitedAdmin_)(nil),
		(*Event_AddedAdmin_)(nil),
		(*Event_RemovedAdmin_)(nil),
		(*Event_RenamedRoom_)(nil),
		(*Event_RecordedScreen_)(nil),
		(*Event_MutedByAdmin_)(nil),
		(*Event_VisibilityUpdated_)(nil),
		(*Event_PinnedLink_)(nil),
		(*Event_UnpinnedLink_)(nil),
		(*Event_OpenedMini_)(nil),
		(*Event_ClosedMini_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		EnumInfos:         file_room_proto_enumTypes,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_rawDesc = nil
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
