// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package room

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomEvent_Type int32

const (
	RoomEvent_JOINED          RoomEvent_Type = 0
	RoomEvent_LEFT            RoomEvent_Type = 1
	RoomEvent_ADDED_SPEAKER   RoomEvent_Type = 2
	RoomEvent_REMOVED_SPEAKER RoomEvent_Type = 3
)

var RoomEvent_Type_name = map[int32]string{
	0: "JOINED",
	1: "LEFT",
	2: "ADDED_SPEAKER",
	3: "REMOVED_SPEAKER",
}

var RoomEvent_Type_value = map[string]int32{
	"JOINED":          0,
	"LEFT":            1,
	"ADDED_SPEAKER":   2,
	"REMOVED_SPEAKER": 3,
}

func (x RoomEvent_Type) String() string {
	return proto.EnumName(RoomEvent_Type_name, int32(x))
}

func (RoomEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0, 0}
}

type RoomCommand_Type int32

const (
	RoomCommand_ADD_SPEAKER    RoomCommand_Type = 0
	RoomCommand_REMOVE_SPEAKER RoomCommand_Type = 1
)

var RoomCommand_Type_name = map[int32]string{
	0: "ADD_SPEAKER",
	1: "REMOVE_SPEAKER",
}

var RoomCommand_Type_value = map[string]int32{
	"ADD_SPEAKER":    0,
	"REMOVE_SPEAKER": 1,
}

func (x RoomCommand_Type) String() string {
	return proto.EnumName(RoomCommand_Type_name, int32(x))
}

func (RoomCommand_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1, 0}
}

type RoomEvent struct {
	Type                 RoomEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=RoomEvent_Type" json:"type,omitempty"`
	From                 string         `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomEvent) Reset()         { *m = RoomEvent{} }
func (m *RoomEvent) String() string { return proto.CompactTextString(m) }
func (*RoomEvent) ProtoMessage()    {}
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *RoomEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomEvent.Unmarshal(m, b)
}
func (m *RoomEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomEvent.Marshal(b, m, deterministic)
}
func (m *RoomEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomEvent.Merge(m, src)
}
func (m *RoomEvent) XXX_Size() int {
	return xxx_messageInfo_RoomEvent.Size(m)
}
func (m *RoomEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoomEvent proto.InternalMessageInfo

func (m *RoomEvent) GetType() RoomEvent_Type {
	if m != nil {
		return m.Type
	}
	return RoomEvent_JOINED
}

func (m *RoomEvent) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type RoomCommand struct {
	Type                 RoomCommand_Type `protobuf:"varint,1,opt,name=type,proto3,enum=RoomCommand_Type" json:"type,omitempty"`
	Data                 []byte           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoomCommand) Reset()         { *m = RoomCommand{} }
func (m *RoomCommand) String() string { return proto.CompactTextString(m) }
func (*RoomCommand) ProtoMessage()    {}
func (*RoomCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *RoomCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCommand.Unmarshal(m, b)
}
func (m *RoomCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCommand.Marshal(b, m, deterministic)
}
func (m *RoomCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCommand.Merge(m, src)
}
func (m *RoomCommand) XXX_Size() int {
	return xxx_messageInfo_RoomCommand.Size(m)
}
func (m *RoomCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCommand proto.InternalMessageInfo

func (m *RoomCommand) GetType() RoomCommand_Type {
	if m != nil {
		return m.Type
	}
	return RoomCommand_ADD_SPEAKER
}

func (m *RoomCommand) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("RoomEvent_Type", RoomEvent_Type_name, RoomEvent_Type_value)
	proto.RegisterEnum("RoomCommand_Type", RoomCommand_Type_name, RoomCommand_Type_value)
	proto.RegisterType((*RoomEvent)(nil), "RoomEvent")
	proto.RegisterType((*RoomCommand)(nil), "RoomCommand")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xea, 0x62, 0xe4, 0xe2, 0x0c, 0xca, 0xcf, 0xcf, 0x75,
	0x2d, 0x4b, 0xcd, 0x2b, 0x11, 0x52, 0xe6, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x33, 0xe2, 0xd7, 0x83, 0xcb, 0xe8, 0x85, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x25, 0x85,
	0x84, 0xb8, 0x58, 0xd2, 0x8a, 0xf2, 0x73, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c,
	0x25, 0x17, 0x2e, 0x16, 0x90, 0x0a, 0x21, 0x2e, 0x2e, 0x36, 0x2f, 0x7f, 0x4f, 0x3f, 0x57, 0x17,
	0x01, 0x06, 0x21, 0x0e, 0x2e, 0x16, 0x1f, 0x57, 0xb7, 0x10, 0x01, 0x46, 0x21, 0x41, 0x2e, 0x5e,
	0x47, 0x17, 0x17, 0x57, 0x97, 0xf8, 0xe0, 0x00, 0x57, 0x47, 0x6f, 0xd7, 0x20, 0x01, 0x26, 0x21,
	0x61, 0x2e, 0xfe, 0x20, 0x57, 0x5f, 0xff, 0x30, 0x24, 0x41, 0x66, 0xa5, 0x52, 0x2e, 0x6e, 0x90,
	0x8d, 0xce, 0xf9, 0xb9, 0xb9, 0x89, 0x79, 0x29, 0x42, 0xaa, 0x28, 0xae, 0x11, 0xd4, 0x43, 0x92,
	0x43, 0x73, 0x4f, 0x4a, 0x62, 0x49, 0x22, 0xd8, 0x3d, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x36, 0xd4,
	0x3d, 0xfc, 0x5c, 0xdc, 0x8e, 0x2e, 0x08, 0x2b, 0x18, 0x84, 0x84, 0xb8, 0xf8, 0x20, 0xf6, 0xc2,
	0xc5, 0x18, 0x93, 0xd8, 0xc0, 0x41, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xa0, 0xfc,
	0x39, 0x18, 0x01, 0x00, 0x00,
}
