// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.pb

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the pb package it is being compiled against.
// A compilation error at this line likely means your copy of the
// pb package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the pb package

type RoomEvent_Type int32

const (
	RoomEvent_JOINED RoomEvent_Type = 0
	RoomEvent_LEFT   RoomEvent_Type = 1
)

var RoomEvent_Type_name = map[int32]string{
	0: "JOINED",
	1: "LEFT",
}

var RoomEvent_Type_value = map[string]int32{
	"JOINED": 0,
	"LEFT":   1,
}

func (x RoomEvent_Type) String() string {
	return proto.EnumName(RoomEvent_Type_name, int32(x))
}

func (RoomEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0, 0}
}

type RoomEvent struct {
	Type                 RoomEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=RoomEvent_Type" json:"type,omitempty"`
	From                 string         `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomEvent) Reset()         { *m = RoomEvent{} }
func (m *RoomEvent) String() string { return proto.CompactTextString(m) }
func (*RoomEvent) ProtoMessage()    {}
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *RoomEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomEvent.Unmarshal(m, b)
}
func (m *RoomEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomEvent.Marshal(b, m, deterministic)
}
func (m *RoomEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomEvent.Merge(m, src)
}
func (m *RoomEvent) XXX_Size() int {
	return xxx_messageInfo_RoomEvent.Size(m)
}
func (m *RoomEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoomEvent proto.InternalMessageInfo

func (m *RoomEvent) GetType() RoomEvent_Type {
	if m != nil {
		return m.Type
	}
	return RoomEvent_JOINED
}

func (m *RoomEvent) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func init() {
	proto.RegisterEnum("RoomEvent_Type", RoomEvent_Type_name, RoomEvent_Type_value)
	proto.RegisterType((*RoomEvent)(nil), "RoomEvent")
}

func init() { proto.RegisterFile("room.pb", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe2, 0xe2, 0x0c, 0xca, 0xcf, 0xcf, 0x75, 0x2d,
	0x4b, 0xcd, 0x2b, 0x11, 0x52, 0xe6, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x33, 0xe2, 0xd7, 0x83, 0xcb, 0xe8, 0x85, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x25, 0x85, 0x84,
	0xb8, 0x58, 0xd2, 0x8a, 0xf2, 0x73, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25,
	0x19, 0x2e, 0x16, 0x90, 0x0a, 0x21, 0x2e, 0x2e, 0x36, 0x2f, 0x7f, 0x4f, 0x3f, 0x57, 0x17, 0x01,
	0x06, 0x21, 0x0e, 0x2e, 0x16, 0x1f, 0x57, 0xb7, 0x10, 0x01, 0xc6, 0x24, 0x36, 0xb0, 0x55, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x8a, 0x66, 0x04, 0x78, 0x00, 0x00, 0x00,
}
